import { Figtree } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/lib/AuthProvider";
import SideBar from "@/components/sideBar/SideBar";
import { Player } from "@/components/player/Player";
import { Provider } from "@radix-ui/react-tooltip";
import { makeStore } from "@/lib/redux/store";
import StoreProvider from "@/components/reduxProvider/ReduxProvider";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate=0;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
      <AuthProvider>
        <StoreProvider>
        <SideBar>
        {children}
          
        </SideBar>
        
        <Player/>
        </StoreProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
