import { Figtree } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import AuthProvider from "@/lib/AuthProvider";
import SideBar from "@/components/sideBar/SideBar";
import { Player } from "@/components/player/Player";
import StoreProvider from "@/components/reduxProvider/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export const revalidate=0;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </head>
      <body className={figtree.className}>
        <AuthProvider>
          <StoreProvider>
            <main className="relative bg-neutral-950">
              <SideBar>{children}</SideBar>
              <Player />
            </main>
            <Toaster position="bottom-center" />
          </StoreProvider>
        </AuthProvider>
        <Analytics/>
      </body>
    </html>
  );
}
